"""Write a deliberately aggregate-only review record for a private model-build workflow.

The source reports generated by the compiler/mixer carry pseudonymous record rows, hashes, relative
filenames, and local paths needed only inside the protected job. This utility selects a small,
non-identifying subset for the GitHub Actions artifact. It never reads media bytes or copies a raw
label, record ID, URL, source path, checkpoint path, or credential into the output.
"""

from __future__ import annotations

import argparse
import json
from collections.abc import Mapping
from pathlib import Path
from typing import Any


class PrivateModelBuildSummaryError(ValueError):
    """Raised when a protected job report cannot form a safe aggregate review record."""


_SPLITS = ("train", "val", "test")
_COUNT_KEYS = (
    "annotationCount",
    "framesWithAllFourCalibrationClasses",
    "framesWithDartAndAllFourCalibrationAnchors",
    "framesWithDartClass0",
    "imageCount",
    "imagesWithoutLabels",
    "labelFileCount",
    "labelsWithoutImages",
    "pairedImageLabelCount",
)


def build_private_model_build_summary(
    *,
    retrieval: Mapping[str, Any],
    real_compilation: Mapping[str, Any],
    synthetic_bootstrap: Mapping[str, Any],
    mixed_dataset: Mapping[str, Any],
    training_summary: Mapping[str, Any] | None = None,
    development_manifest: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    """Return a non-identifying review record suitable for a short-lived CI artifact."""

    retrieved = _retrieval_summary(retrieval)
    real = _real_summary(real_compilation)
    synthetic = _synthetic_summary(synthetic_bootstrap)
    mixed = _mixed_summary(mixed_dataset)
    model = _model_summary(training_summary, development_manifest)

    return {
        "schemaVersion": 1,
        "scope": (
            "aggregate-only private Darts 180 model-build review record; contains no raw media, "
            "record IDs, URLs, file paths, labels, checkpoints, or credentials"
        ),
        "outcome": "trained-development-artifact" if model is not None else "prepared-for-review",
        "privateCaptureRetrieval": retrieved,
        "realCompilation": real,
        "syntheticBootstrap": synthetic,
        "mixedDataset": mixed,
        "model": model,
        "releaseSafety": {
            "productionReady": False,
            "mustRemainEditable": True,
            "realValidationAndTestOnly": True,
            "requiresSeparateArtifactAndPhoneReviewBeforeInstall": True,
            "doesNotAuthorizePrivateRecordExportOrDeployment": True,
        },
    }


def _retrieval_summary(value: Mapping[str, Any]) -> dict[str, Any]:
    _require_schema_version(value, "retrieval")
    record_count = _non_negative_int(value.get("recordCount"), "retrieval.recordCount")
    asset_count = _asset_counts(value.get("assetCount"), "retrieval.assetCount")
    if any(count != record_count for count in asset_count.values()):
        raise PrivateModelBuildSummaryError(
            "The retrieval receipt does not contain one complete asset triplet per approved record."
        )
    return {
        "recordCount": record_count,
        "assetCount": asset_count,
        "byteCount": _asset_counts(value.get("byteCount"), "retrieval.byteCount"),
    }


def _real_summary(value: Mapping[str, Any]) -> dict[str, Any]:
    if value.get("compilationVersion") != 1:
        raise PrivateModelBuildSummaryError("The real compilation report has an unsupported version.")
    split_image_counts = _split_counts(value.get("splitImageCounts"), "real.splitImageCounts")
    split_session_counts = _split_counts(value.get("splitSessionCounts"), "real.splitSessionCounts")
    if any(count < 1 for count in split_image_counts.values()) or any(
        count < 1 for count in split_session_counts.values()
    ):
        raise PrivateModelBuildSummaryError(
            "The real compilation needs at least one image and one whole setup session in each split."
        )
    return {
        "annotationMethod": _string(value.get("annotationMethod"), "real.annotationMethod"),
        "annotationProfile": _string(value.get("annotationProfile"), "real.annotationProfile"),
        "classMap": _class_map(value.get("classMap"), "real.classMap"),
        "splitImageCounts": split_image_counts,
        "splitSessionCounts": split_session_counts,
        "labelCounts": _named_counts(value.get("labelCounts"), "real.labelCounts"),
        "labelIntegrityIssueCount": _issue_count(value.get("structuralAudit"), "real"),
    }


def _synthetic_summary(value: Mapping[str, Any]) -> dict[str, Any]:
    provenance = _mapping(value.get("syntheticProvenance"), "synthetic.syntheticProvenance")
    if provenance.get("containsHumanCapture") is not False:
        raise PrivateModelBuildSummaryError("The bootstrap report does not exclude human captures.")
    if provenance.get("containsAiGeneratedWholeBoardPhotos") is not False:
        raise PrivateModelBuildSummaryError(
            "The bootstrap report does not explicitly exclude AI-generated whole-board photos."
        )
    if provenance.get("realWorldEvaluationEligible") is not False:
        raise PrivateModelBuildSummaryError(
            "The bootstrap report must not claim real-world evaluation eligibility."
        )
    return {
        "profile": _string(provenance.get("profile"), "synthetic.profile"),
        "containsHumanCapture": False,
        "realWorldEvaluationEligible": False,
        "splitImageCounts": _split_counts(
            value.get("splitImageCounts"), "synthetic.splitImageCounts"
        ),
        "labelCounts": _named_counts(value.get("labelCounts"), "synthetic.labelCounts"),
        "labelIntegrityIssueCount": _issue_count(value.get("structuralAudit"), "synthetic"),
    }


def _mixed_summary(value: Mapping[str, Any]) -> dict[str, Any]:
    if value.get("mixingVersion") != 1:
        raise PrivateModelBuildSummaryError("The mixed dataset report has an unsupported version.")
    provenance = _mapping(value.get("mixedProvenance"), "mixed.mixedProvenance")
    evaluation = _mapping(provenance.get("evaluation"), "mixed.evaluation")
    synthetic = _mapping(provenance.get("synthetic"), "mixed.synthetic")
    real = _mapping(provenance.get("real"), "mixed.real")
    if provenance.get("trainingDataKind") != "mixed-synthetic-and-real":
        raise PrivateModelBuildSummaryError("The mixed report has the wrong data kind.")
    if evaluation.get("validationContainsOnlyReviewedReal") is not True:
        raise PrivateModelBuildSummaryError("Mixed validation is not limited to reviewed real records.")
    if evaluation.get("testContainsOnlyReviewedReal") is not True:
        raise PrivateModelBuildSummaryError("Mixed test is not limited to reviewed real records.")
    if evaluation.get("productionReady") is not False:
        raise PrivateModelBuildSummaryError("A development mixed data set cannot be production-ready.")
    if synthetic.get("usedForTrainingOnly") is not True:
        raise PrivateModelBuildSummaryError("Synthetic records are not restricted to training.")
    if synthetic.get("realWorldEvaluationEligible") is not False:
        raise PrivateModelBuildSummaryError("Synthetic records may not be eligible for real-world evaluation.")
    reviewed_real_counts = _split_counts(
        real.get("includedImageCounts"), "mixed.real.includedImageCounts"
    )
    synthetic_counts = _split_counts(
        synthetic.get("includedImageCounts"), "mixed.synthetic.includedImageCounts"
    )
    if any(count < 1 for count in reviewed_real_counts.values()):
        raise PrivateModelBuildSummaryError(
            "Mixed data requires reviewed real images in train, validation, and test."
        )
    if synthetic_counts["train"] < 1 or synthetic_counts["val"] != 0 or synthetic_counts["test"] != 0:
        raise PrivateModelBuildSummaryError(
            "Mixed synthetic examples must exist only in the training split."
        )

    return {
        "trainingDataKind": "mixed-synthetic-and-real",
        "classMap": _class_map(value.get("classMap"), "mixed.classMap"),
        "splitImageCounts": _split_counts(value.get("splitImageCounts"), "mixed.splitImageCounts"),
        "labelCountsByClassId": _named_counts(
            value.get("labelCountsByClassId"), "mixed.labelCountsByClassId"
        ),
        "reviewedRealImageCounts": reviewed_real_counts,
        "syntheticIncludedImageCounts": synthetic_counts,
        "evaluation": {
            "validationContainsOnlyReviewedReal": True,
            "testContainsOnlyReviewedReal": True,
            "productionReady": False,
        },
        "labelIntegrityIssueCount": _issue_count(value.get("structuralAudit"), "mixed"),
        "aggregateStructuralCounts": _audit_aggregate(value.get("structuralAudit"), "mixed"),
    }


def _model_summary(
    training_summary: Mapping[str, Any] | None,
    development_manifest: Mapping[str, Any] | None,
) -> dict[str, Any] | None:
    if training_summary is None and development_manifest is None:
        return None
    if training_summary is None or development_manifest is None:
        raise PrivateModelBuildSummaryError(
            "A trained-artifact summary requires both the training summary and development manifest."
        )
    if training_summary.get("trainingDataKind") != "mixed-synthetic-and-real":
        raise PrivateModelBuildSummaryError("The training summary has the wrong data kind.")
    if development_manifest.get("releaseStage") != "development":
        raise PrivateModelBuildSummaryError("Only a development-stage manifest may be summarized here.")
    if development_manifest.get("modelId") != "darts180-deepdarts-yolo":
        raise PrivateModelBuildSummaryError("Unexpected model ID in the development manifest.")
    return {
        "modelId": "darts180-deepdarts-yolo",
        "modelVersion": _string(development_manifest.get("modelVersion"), "model.modelVersion"),
        "releaseStage": "development",
        "onnxSha256": _sha256(development_manifest.get("sha256"), "model.onnxSha256"),
        "trainingDataKind": "mixed-synthetic-and-real",
        "trainedAt": _string(development_manifest.get("provenance", {}).get("trainedAt"), "model.trainedAt")
        if isinstance(development_manifest.get("provenance"), Mapping)
        else _raise("model.provenance must be an object."),
    }


def read_json_object(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as error:
        raise PrivateModelBuildSummaryError("A required private build report could not be read.") from error
    return dict(_mapping(value, "report"))


def _require_schema_version(value: Mapping[str, Any], label: str) -> None:
    if value.get("schemaVersion") != 1:
        raise PrivateModelBuildSummaryError(f"The {label} receipt has an unsupported version.")


def _asset_counts(value: Any, label: str) -> dict[str, int]:
    mapping = _mapping(value, label)
    return {
        kind: _non_negative_int(mapping.get(kind), f"{label}.{kind}")
        for kind in ("image", "manifest", "annotations")
    }


def _split_counts(value: Any, label: str) -> dict[str, int]:
    mapping = _mapping(value, label)
    return {
        split: _non_negative_int(mapping.get(split), f"{label}.{split}") for split in _SPLITS
    }


def _named_counts(value: Any, label: str) -> dict[str, int]:
    mapping = _mapping(value, label)
    result: dict[str, int] = {}
    for key, count in mapping.items():
        if not isinstance(key, str) or not key:
            raise PrivateModelBuildSummaryError(f"{label} has an invalid count name.")
        result[key] = _non_negative_int(count, f"{label}.{key}")
    return dict(sorted(result.items()))


def _class_map(value: Any, label: str) -> dict[str, int]:
    mapping = _mapping(value, label)
    expected = {
        "dartEntryPoint": 0,
        "calibration1": 1,
        "calibration2": 2,
        "calibration3": 3,
        "calibration4": 4,
    }
    if dict(mapping) != expected:
        raise PrivateModelBuildSummaryError(f"{label} does not match the fixed five-point class map.")
    return expected


def _issue_count(value: Any, label: str) -> int:
    audit = _mapping(value, f"{label}.structuralAudit")
    integrity = _mapping(audit.get("labelIntegrity"), f"{label}.labelIntegrity")
    return _non_negative_int(integrity.get("count"), f"{label}.labelIntegrity.count")


def _audit_aggregate(value: Any, label: str) -> dict[str, int]:
    audit = _mapping(value, f"{label}.structuralAudit")
    aggregate = _mapping(audit.get("aggregate"), f"{label}.aggregate")
    return {
        key: _non_negative_int(aggregate.get(key), f"{label}.aggregate.{key}")
        for key in _COUNT_KEYS
    }


def _mapping(value: Any, label: str) -> Mapping[str, Any]:
    if not isinstance(value, Mapping):
        raise PrivateModelBuildSummaryError(f"{label} must be an object.")
    return value


def _non_negative_int(value: Any, label: str) -> int:
    if not isinstance(value, int) or isinstance(value, bool) or value < 0:
        raise PrivateModelBuildSummaryError(f"{label} must be a non-negative integer.")
    return value


def _string(value: Any, label: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise PrivateModelBuildSummaryError(f"{label} must be a non-empty string.")
    return value.strip()


def _sha256(value: Any, label: str) -> str:
    if (
        not isinstance(value, str)
        or len(value) != 64
        or any(character not in "0123456789abcdef" for character in value)
    ):
        raise PrivateModelBuildSummaryError(f"{label} must be a lowercase SHA-256 string.")
    return value


def _raise(message: str) -> Any:
    raise PrivateModelBuildSummaryError(message)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Write a sanitized aggregate review record for a private Darts 180 model build."
    )
    parser.add_argument("--retrieval", required=True, type=Path)
    parser.add_argument("--real-compilation", required=True, type=Path)
    parser.add_argument("--synthetic-bootstrap", required=True, type=Path)
    parser.add_argument("--mixed-dataset", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--training-summary", type=Path)
    parser.add_argument("--development-manifest", type=Path)
    args = parser.parse_args()

    if (args.training_summary is None) != (args.development_manifest is None):
        raise SystemExit(
            "--training-summary and --development-manifest must be supplied together after training."
        )
    try:
        summary = build_private_model_build_summary(
            retrieval=read_json_object(args.retrieval),
            real_compilation=read_json_object(args.real_compilation),
            synthetic_bootstrap=read_json_object(args.synthetic_bootstrap),
            mixed_dataset=read_json_object(args.mixed_dataset),
            training_summary=(
                read_json_object(args.training_summary) if args.training_summary is not None else None
            ),
            development_manifest=(
                read_json_object(args.development_manifest)
                if args.development_manifest is not None
                else None
            ),
        )
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    except PrivateModelBuildSummaryError as error:
        raise SystemExit(f"Private model build summary was not written: {error}") from error


if __name__ == "__main__":
    main()
